import type { Metadata } from "next";
import Link from "next/link";
import SeoPage from "@/components/SeoPage";
import JsonLd from "@/components/JsonLd";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"قیمت سکه امروز | قیمت سکه امامی",description:"قیمت روز سکه امامی به تومان، تغییرات قیمت و آخرین زمان دریافت نرخ در روزگار.",alternates:{canonical:"/coin"},openGraph:{title:"قیمت سکه امروز | روزگار",description:"مشاهده قیمت به‌روز سکه امامی به تومان در روزگار.",url:"https://www.qolet.ir/coin",type:"website"}};
type Market={emamiCoinToman?:{toman:number;changePercent:number;rising:boolean};fetchedAt?:number};
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n));
async function getMarket():Promise<Market|null>{try{const r=await fetch("https://www.qolet.ir/api/market",{cache:"no-store"});if(!r.ok)return null;return await r.json()}catch{return null}}
export default async function CoinPage(){const d=await getMarket();const c=d?.emamiCoinToman;const u=d?.fetchedAt?new Date(d.fetchedAt).toISOString():undefined;const schema={"@context":"https://schema.org","@type":"Dataset",name:"قیمت امروز سکه امامی",description:"قیمت به‌روز سکه امامی به تومان در روزگار.",url:"https://www.qolet.ir/coin",inLanguage:"fa-IR"};return <SeoPage><JsonLd data={schema}/><section className="seo-hero"><span className="seo-kicker">روزگار · بازار</span><h1>قیمت سکه امروز</h1><p>قیمت سکه امامی را به تومان ببینید و تغییرات روزانه آن را دنبال کنید.</p></section><section className="seo-grid"><article className="seo-card"><h2>سکه امامی</h2><p className="seo-price">{c?fa(c.toman)+" تومان":"در حال دریافت قیمت..."}</p><p>{c?(c.rising?"افزایش ":"کاهش ")+fa(Math.abs(c.changePercent))+"٪ نسبت به آخرین مقدار ثبت‌شده":"قیمت فعلاً در دسترس نیست."}</p></article><article className="seo-card"><h2>قیمت طلا و سکه</h2><p>در روزگار می‌توانید قیمت طلا، دلار و سکه را در صفحات اختصاصی بازار دنبال کنید.</p><p><Link className="seo-link" href="/gold">قیمت طلا ←</Link></p></article></section><section className="seo-section"><h2>سؤالات رایج</h2><div className="seo-grid"><article className="seo-card"><h3>قیمت سکه امامی چقدر است؟</h3><p>نرخ فعلی در کارت بالای صفحه نمایش داده می‌شود و از سرویس بازار دریافت می‌شود.</p></article><article className="seo-card"><h3>قیمت سکه به چه واحدی است؟</h3><p>قیمت این صفحه به تومان نمایش داده می‌شود.</p></article></div></section></SeoPage>}