import type { Metadata } from "next";
import Link from "next/link";
import SeoPage from "@/components/SeoPage";
import JsonLd from "@/components/JsonLd";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"قیمت دلار امروز | نرخ دلار به تومان",description:"نرخ لحظه‌ای دلار به تومان، درصد تغییر و آخرین زمان دریافت قیمت در روزگار.",alternates:{canonical:"/dollar"},openGraph:{title:"قیمت دلار امروز | روزگار",description:"مشاهده نرخ به‌روز دلار به تومان در روزگار.",url:"https://www.qolet.ir/dollar",type:"website"}};
type Market={usdToman?:{toman:number;changePercent:number;rising:boolean};fetchedAt?:number};
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n));
async function getMarket():Promise<Market|null>{try{const r=await fetch("https://www.qolet.ir/api/market",{cache:"no-store"});if(!r.ok)return null;return await r.json()}catch{return null}}
export default async function DollarPage(){const d=await getMarket();const x=d?.usdToman;const u=d?.fetchedAt?new Date(d.fetchedAt).toLocaleTimeString("fa-IR",{hour:"2-digit",minute:"2-digit"}):null;return <SeoPage><JsonLd data={{"@context":"https://schema.org","@type":"Dataset",name:"قیمت امروز دلار",description:"نرخ به‌روز دلار به تومان در روزگار.",url:"https://www.qolet.ir/dollar",inLanguage:"fa-IR"}}/><section className="seo-hero"><span className="seo-kicker">روزگار · بازار</span><h1>قیمت دلار امروز</h1><p>نرخ دلار به تومان و تغییرات روزانه را در یک صفحه سریع مشاهده کنید.</p></section><section className="seo-grid"><article className="seo-card"><h2>دلار</h2><p className="seo-price">{x?fa(x.toman)+" تومان":"در حال دریافت قیمت..."}</p><p>{x?(x.rising?"افزایش ":"کاهش ")+fa(Math.abs(x.changePercent))+"٪ نسبت به آخرین مقدار ثبت‌شده":"نرخ فعلاً در دسترس نیست."}</p>{u&&<p className="seo-muted">آخرین دریافت: {u}</p>}</article><article className="seo-card"><h2>نرخ دلار به تومان</h2><p>صفحه اختصاصی روزگار برای مشاهده نرخ دلار و دسترسی مستقیم به تقویم و ابزارهای روزانه.</p><p><Link className="seo-link" href="/">بازگشت به روزگار ←</Link></p></article></section><section className="seo-section"><h2>سؤالات رایج</h2><div className="seo-grid"><article className="seo-card"><h3>قیمت دلار امروز چطور نمایش داده می‌شود؟</h3><p>نرخ از سرویس بازار روزگار دریافت و به تومان نمایش داده می‌شود.</p></article><article className="seo-card"><h3>آیا نرخ ثابت است؟</h3><p>خیر؛ بازار تغییر می‌کند و صفحه هنگام دریافت داده مقدار جدید را نمایش می‌دهد.</p></article></div></section></SeoPage>}